sudo: false
install: true

os:
  - linux

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "2.6"
    - python: "nightly"

branches:
  only:
  - master

before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -y python python-pip

before_script:
  - sudo pip install -r requirements.txt

script:
- make test && make clean && make && ./sipd -t
